version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs


sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py
